### ISSUE TITLE
Search function for the individual forums

### ISSUE THREAD

**Issue by atakee72** [atakee72/Community-Web-Forum-App-with-Next.js#1]
Task list example: 
- [ ] look at the HTML and logic in the prototype
- [ ] compare with the Next.js solution if any
- [ ] apply in the first forum
- [ ] replicate and adapt in others forums and done
- [ ] Extras: consider keyword etc. search, e.g. as regards labels, probably by creating a new feature branch

**Comment by atakee72** [comment]
```[tasklist]
### Tasks
- [ ] Check the previous version as to HTML and logic
```

**Comment by atakee72** [comment]
Celebrate the first issue ever! :)
